//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hackncEntities : DbContext
    {
        public hackncEntities()
            : base("name=hackncEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories1 { get; set; }
        public virtual DbSet<Customer> Customers1 { get; set; }
        public virtual DbSet<Inventory> Inventories1 { get; set; }
        public virtual DbSet<Item> Items1 { get; set; }
        public virtual DbSet<Location> Locations1 { get; set; }
        public virtual DbSet<Recipe> Recipes1 { get; set; }
        public virtual DbSet<Transaction> Transactions1 { get; set; }
        public virtual DbSet<Vendor> Vendors1 { get; set; }
    }
}
