//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.transactions = new HashSet<Transaction>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid location_id { get; set; }
        public long units { get; set; }
        public decimal price_per_unit { get; set; }
        public decimal cost_per_unit { get; set; }
        public System.Guid item_id { get; set; }
    
        public virtual Item item { get; set; }
        public virtual ICollection<Transaction> transactions { get; set; }
    }
}
