//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.inventory = new HashSet<Inventory>();
            this.transactions = new HashSet<Transaction>();
        }
    
        public System.Guid ID { get; set; }
        public long sku { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public bool is_recipe { get; set; }
        public Nullable<System.Guid> category_id { get; set; }
    
        public virtual Category category { get; set; }
        public virtual ICollection<Inventory> inventory { get; set; }
        public virtual ICollection<Transaction> transactions { get; set; }
    }
}
