//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public System.Guid recipe_item_id { get; set; }
        public System.Guid item_id { get; set; }
        public long units { get; set; }
    
        public virtual Item id { get; set; }
        public virtual Item item { get; set; }
    }
}
