//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
        }
    
        public System.Guid id { get; set; }
        public Location location { get; set; }
        public long units { get; set; }
        public decimal pricePerUnit { get; set; }
        public decimal costPerPnit { get; set; }    
        public Item item { get; set; }
    }
}
