//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
        }
    
        public System.Guid id { get; set; }
        public long sku { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public bool isRecipe { get; set; }
    
        public Category category { get; set; }
    }
}
