//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid id { get; set; }
        public Inventory inventory { get; set; }
        public Location location { get; set; }
        public decimal price { get; set; }
        public decimal cost { get; set; }
        public DateTime time { get; set; }
    }
}
